export const API = {
  LOGIN: "auth/login",
  REGISTER: "auth/users",
  USER_INFO: "users/self",
  GET_QUESTIONS: "questions",
  GET_ANSWERS: "path",
  SUBMIT_ANSWER: "path",
  GET_USERS: "users",
  GET_QUIZZES: "quizzes",
  QUIZ_FILLED: "quiz/filled",

  NEXT_QUESTION_SUCCESS: "path",
  NEXT_QUESTION_ERROR: "path",
  CHECK_CORRECT_ANSWER_FAILED: "path",
  CHECK_CORRECT_ANSWER_SUCESS: "path"
};

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";

export const GET_QUIZZES_SUCCESS = "GET_QUIZZES_SUCCESS";
export const GET_QUIZZES_ERROR = "GET_QUIZZES_ERROR";

export const QUIZ_FILLED_SUCCESS = "QUIZ_FILLED_SUCCESS";
export const QUIZ_FILLED_ERROR = " QUIZ_FILLED_ERROR";

export const NEXT_QUESTION_SUCCESS = "NEXT_QUESTION_SUCCESS";
export const NEXT_QUESTION_ERROR = "NEXT_QUESTION_ERROR";

export const CHECK_CORRECT_ANSWER_FAILED = "CHECK_CORRECT_ANSWER_FAILED";
export const CHECK_CORRECT_ANSWER_SUCCESS = "CHECK_CORRECT_ANSWER_SUCCESS";
