export const API = {
    LOGIN: "auth/login",
    REGISTER: "auth/users",
    USER_INFO: "users/self",
    GET_QUESTIONS: "path",
    GET_ANSWERS: "path",
    SUBMIT_ANSWER: "path",
    GET_USERS: "path",

    STORE_ANSWERS_SUCCESS: "path",
    STORE_ANSWERS_ERROR: "path",
    CHECK_CORRECT_ANSWER_FAILED: "path",
    CHECK_CORRECT_ANSWER_SUCESS: "path"
};

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";

export const STORE_ANSWERS_SUCCESS = "STORE_ANSWERS_SUCCESS";
export const STORE_ANSWERS_ERROR = "STORE_ANSWERS_ERROR";

export const CHECK_CORRECT_ANSWER_FAILED = "CHECK_CORRECT_ANSWER_FAILED";
export const CHECK_CORRECT_ANSWER_SUCCESS = "CHECK_CORRECT_ANSWER_SUCCESS";
